name: Event Notifier

on:
  issues:
    types: [opened, labeled, reopened]
  pull_request_target:
    types: [opened, reopened] # zizmor: ignore[dangerous-triggers]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  issues: read
  pull-requests: read

jobs:
  notify:
    name: "Telegram notification"
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram notification for new issue or pull request
        uses: sehat1137/telegram-notifier@0942904cfa8775e115be93f3a1e39b365178d8f0 # v1.5.1
        with:
          tg-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          tg-chat-id: ${{ vars.TELEGRAM_CHAT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
